### ISSUE TITLE
[BUG] Update `nuget-icon`

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/opensearch-net-abstractions#7]
Use [opensearch_mark_default.png ](https://github.com/opensearch-project/project-website/blob/main/assets/brand/PNG/Mark/opensearch_mark_default.png) to replace [nuget-icon.png](https://github.com/opensearch-project/opensearch-net-abstractions/blob/main/nuget-icon.png).

**Comment by Yury-Fridlyand** [comment]
Fixed in #9

**Comment by AMoo-Miki** [comment]
Thanks @Yury-Fridlyand.
